# 01_creat 测试
creat: 01_creat.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 02_sum_sqr 测试
sum_sqr: 02_sum_sqr.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 03_sum_sqr_thread 测试
sum_sqr_thread: 03_sum_sqr_thread.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 04_cancel_no 测试
cancel_no: 04_cancel_no.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 05_cancel_yes 测试
cancel_yes: 05_cancel_yes.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 06_race 测试
race: 06_race.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@

# 07_mutex_lock 测试
mutex_lock: 07_mutex_lock.c
	-gcc -o $@ $^
	-./$@
	-rm -f $@
